- name: Install mysql-server
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: Start mysql server service
  ansible.builtin.systemd_service:
    state: started
    name: mysqld

- name: SetUp mysql Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1