- name: Frontend expense setup
  hosts: all
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        state: latest

    - name: Start nginx
      ansible.builtin.systemd_service:
        state: restarted
        name: nginx


