- name: Disable nodejs
  ansible.builtin.shell: dnf module disable nodejs -y
- name: Enable nodejs
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Install nodejs
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Add Application user
  ansible.builtin.user:
    name: expense

#- name: Load backend service
#  ansible.builtin.copy:
#    src: backend.service
#    dest: /etc/systemd/system/backend.service

- name: Load backend service
    ansible.builtin.template:
      src: backend.service
      dest: /etc/systemd/system/backend.service

- name: Run tasks/other.yaml instead of 'main'
  ansible.builtin.import_role:
    name: common
    tasks_from: pre_req_code

- name: Install npm package
  community.general.npm:
    name: npm
    path: /app

- name: Install mysql
  ansible.builtin.dnf:
    name: mysql
    state: latest
- name: Install Python pkgs
  ansible.builtin.pip:
    name:
      - PyMySQL
      - Cryptography

- name: Load schema
  community.mysql.mysql_db:
    name: all
    state: import
    target: /app/schema/backend.sql
    login_user: root
    login_password: ExpenseApp@1
    login_host: mysql-dev.pdevops72.online

- name: Restart daemon service
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name:  backend