- name: Store data into variable
  hosts: localhost
  tasks:
    - name: substitution of variable
      ansible.builtin.shell: uptime
      register: OUTPUT

    - name: display variable
      ansible.builtin.debug:
        msg: "{{ OUTPUT.failed }}"
        when: OUTPUT.failed is true
        ignore_errors: yes